apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Socle commun aux namespaces prod et staging .
# Le namespace est fixé par chaque overlay.
resources:
  - resourcequota.yaml
  - limitrange.yaml
  - rbac.yaml
  - networkpolicies.yaml
